<template>
  <div id="app">

    <!--
      TEMPLATE

    <div class="my-vue-experiment">

    </div>
    -->


    <!-- Navigation Example 2 -->
    <!-- UNSUCCESSFUL -->
    <!-- <div class="my-vue-experiment">
      <h1>Navigation Test 2</h1>
      <NavTestTwo/>
    </div> -->

    <!-- Navigation Example 1 -->
    <!-- UNSUCCESSFUL -->
    <!-- <div class="my-vue-experiment">
      <h1>Navigation Test 1</h1>
      <NavTestOne/>
    </div> -->

    <!-- Carousel Example -->
    <div class="my-vue-experiment">
      <h1>Hello Carousel</h1>
      <CarouselTest/>
    </div>

    <!-- Default Hello World Generated by VUE CLI -->
    <div class="my-vue-experiment">
      <img alt="Vue logo" src="./assets/logo.png">
      <HelloWorld msg="Welcome to Your Vue.js App"/>
    </div>

  </div>
</template>

<script>
import Vue from 'vue'
import HelloWorld from './components/HelloWorld.vue'
import CarouselTest from './components/CarouselTest.vue'
// import NavTestTwo from './components/NavTestTwo.vue'

// import NavTestOne from './components/NavTestOne.vue'
// import VueRouter from 'vue-router'
// import doo from './components/NavTestOneRouteComponents/doo'
// import foo from './components/NavTestOneRouteComponents/foo.vue'
// Vue.config.productionTip = false
// Vue.use(VueRouter);
// const routes = [
//   { path: '/foo', component: foo },
//   { path: '/doo', component: doo }
// ];
// const router = new VueRouter({
//   routes
// });
// export default {
//   name: 'app',
//   router,
//   components: {
//     HelloWorld,
//     CarouselTest,
//     NavTestOne,
//     NavTestTwo
//   }
// }

export default {
  name: 'app',
  components: {
    HelloWorld,
    CarouselTest,
    // NavTestTwo
  }
}
</script>

<style>
.my-vue-experiment {
  width: 100%;
  height: 600px;
  border-bottom: medium dashed blue;
}

#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
